version: '3.8'
services:
  mysql:
    image: mysql:8.0.31-debian
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=cavelinker_database
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  cavelinkerserver:
    image: cavelinkerserver:1.0
    ports:
      - 8080:8080
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_JDBC_URL=jdbc:mysql://mysql:3306/cavelinker_database
    depends_on:
      - "mysql"
